language: php

php:
  - 5.6

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

services:
  - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - mysql -e 'create database if not exists test;'
  - mysql -e 'use test; create table if not exists Person (id int unsigned auto_increment primary key, first_name varchar(30) not null, last_name varchar(30) not null, age int(2), gender varchar(7) );'

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
  - vendor/bin/coveralls -v
